version: '2.0'

services:
  dpp:
    build: .
    restart: always
    ports:
      - '220:22'
    volumes:
      - ./data:/home/build
      - ./ssh:/etc/ssh
    networks:
      - 'database'

networks:
  database:
    external: true

